version: "3"
services:
    flask_text_reader:
        container_name: flask_text_reader
        restart: always
        build: ./
        image: flask-text-reader
        env_file:
            - ./.env
        labels:
            - traefik.http.routers.log_reader.rule=Host(`${SUBDOMAIN_LOG}`)
            - traefik.http.routers.log_reader.middlewares=auth
            - traefik.http.middlewares.auth.basicauth.users=${AUTH_USER_PASSWORD}
        volumes:
            - ${FILE_DIR}:${FILE_DIR}:rw
        ports:
            - "8050:8050"
