version: "3"
services:
    flask_text_reader:
        container_name: flask_text_reader
        restart: always
        build: ./
        image: flask-text-reader
        env_file:
            - ./.env
        labels:
            - traefik.backend=flask-text-reader
            - traefik.port=8050
            - traefik.frontend.rule=Host:${SUBDOMAIN_LOG}
            - traefik.frontend.auth.basic.users=${AUTH_USER_PASSWORD}
        volumes:
            - ${FILE_DIR}:${FILE_DIR}:rw
        ports:
            - "8050:8050"
